/*
 * This file is generated by jOOQ.
 */
package nl.lawinegevaar.yahoogroups.database.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>SQL$DEFAULT</code>
     */
    public static final Sequence<Long> SQL$DEFAULT = Internal.createSequence("SQL$DEFAULT", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT, null, 0, null, null, false, null);
}
