/*
 * This file is generated by jOOQ.
 */
package nl.lawinegevaar.yahoogroups.database.jooq;


import nl.lawinegevaar.yahoogroups.database.jooq.tables.Dbversion;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.LinkInfo;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.PostInformation;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.Rawdata;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.SitemapLinks;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.Ygroup;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DBVERSION</code>.
     */
    public static final Dbversion DBVERSION = Dbversion.DBVERSION;

    /**
     * The table <code>LINK_INFO</code>.
     */
    public static final LinkInfo LINK_INFO = LinkInfo.LINK_INFO;

    /**
     * The table <code>POST_INFORMATION</code>.
     */
    public static final PostInformation POST_INFORMATION = PostInformation.POST_INFORMATION;

    /**
     * The table <code>RAWDATA</code>.
     */
    public static final Rawdata RAWDATA = Rawdata.RAWDATA;

    /**
     * The table <code>SITEMAP_LINKS</code>.
     */
    public static final SitemapLinks SITEMAP_LINKS = SitemapLinks.SITEMAP_LINKS;

    /**
     * The table <code>YGROUP</code>.
     */
    public static final Ygroup YGROUP = Ygroup.YGROUP;
}
