/*
 * This file is generated by jOOQ.
 */
package nl.lawinegevaar.yahoogroups.database.jooq;


import javax.annotation.processing.Generated;

import nl.lawinegevaar.yahoogroups.database.jooq.tables.Dbversion;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.LinkInfo;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.PostInformation;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.Rawdata;
import nl.lawinegevaar.yahoogroups.database.jooq.tables.Ygroup;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DBVERSION</code>.
     */
    public static final Dbversion DBVERSION = Dbversion.DBVERSION;

    /**
     * The table <code>LINK_INFO</code>.
     */
    public static final LinkInfo LINK_INFO = LinkInfo.LINK_INFO;

    /**
     * The table <code>POST_INFORMATION</code>.
     */
    public static final PostInformation POST_INFORMATION = PostInformation.POST_INFORMATION;

    /**
     * The table <code>RAWDATA</code>.
     */
    public static final Rawdata RAWDATA = Rawdata.RAWDATA;

    /**
     * The table <code>YGROUP</code>.
     */
    public static final Ygroup YGROUP = Ygroup.YGROUP;
}
