/*
 * This file is generated by jOOQ.
 */
package nl.lawinegevaar.yahoogroups.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import nl.lawinegevaar.yahoogroups.database.jooq.tables.Dbversion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbversionRecord extends UpdatableRecordImpl<DbversionRecord> implements Record2<Integer, Timestamp> {

    private static final long serialVersionUID = 1243852642;

    /**
     * Setter for <code>DBVERSION.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DBVERSION.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DBVERSION.MIGRATION_DATE</code>.
     */
    public void setMigrationDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>DBVERSION.MIGRATION_DATE</code>.
     */
    public Timestamp getMigrationDate() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Dbversion.DBVERSION.VERSION;
    }

    @Override
    public Field<Timestamp> field2() {
        return Dbversion.DBVERSION.MIGRATION_DATE;
    }

    @Override
    public Integer component1() {
        return getVersion();
    }

    @Override
    public Timestamp component2() {
        return getMigrationDate();
    }

    @Override
    public Integer value1() {
        return getVersion();
    }

    @Override
    public Timestamp value2() {
        return getMigrationDate();
    }

    @Override
    public DbversionRecord value1(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public DbversionRecord value2(Timestamp value) {
        setMigrationDate(value);
        return this;
    }

    @Override
    public DbversionRecord values(Integer value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbversionRecord
     */
    public DbversionRecord() {
        super(Dbversion.DBVERSION);
    }

    /**
     * Create a detached, initialised DbversionRecord
     */
    public DbversionRecord(Integer version, Timestamp migrationDate) {
        super(Dbversion.DBVERSION);

        set(0, version);
        set(1, migrationDate);
    }
}
