/*
 * This file is generated by jOOQ.
 */
package nl.lawinegevaar.yahoogroups.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import nl.lawinegevaar.yahoogroups.database.jooq.tables.Rawdata;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RawdataRecord extends UpdatableRecordImpl<RawdataRecord> implements Record5<Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = -560899431;

    /**
     * Setter for <code>RAWDATA.GROUP_ID</code>.
     */
    public void setGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>RAWDATA.GROUP_ID</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>RAWDATA.MESSAGE_ID</code>.
     */
    public void setMessageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>RAWDATA.MESSAGE_ID</code>.
     */
    public Integer getMessageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>RAWDATA.MESSAGE_JSON</code>.
     */
    public void setMessageJson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>RAWDATA.MESSAGE_JSON</code>.
     */
    public String getMessageJson() {
        return (String) get(2);
    }

    /**
     * Setter for <code>RAWDATA.RAW_MESSAGE_JSON</code>.
     */
    public void setRawMessageJson(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>RAWDATA.RAW_MESSAGE_JSON</code>.
     */
    public String getRawMessageJson() {
        return (String) get(3);
    }

    /**
     * Setter for <code>RAWDATA.LAST_UPDATE</code>.
     */
    public void setLastUpdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>RAWDATA.LAST_UPDATE</code>.
     */
    public Timestamp getLastUpdate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Rawdata.RAWDATA.GROUP_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Rawdata.RAWDATA.MESSAGE_ID;
    }

    @Override
    public Field<String> field3() {
        return Rawdata.RAWDATA.MESSAGE_JSON;
    }

    @Override
    public Field<String> field4() {
        return Rawdata.RAWDATA.RAW_MESSAGE_JSON;
    }

    @Override
    public Field<Timestamp> field5() {
        return Rawdata.RAWDATA.LAST_UPDATE;
    }

    @Override
    public Integer component1() {
        return getGroupId();
    }

    @Override
    public Integer component2() {
        return getMessageId();
    }

    @Override
    public String component3() {
        return getMessageJson();
    }

    @Override
    public String component4() {
        return getRawMessageJson();
    }

    @Override
    public Timestamp component5() {
        return getLastUpdate();
    }

    @Override
    public Integer value1() {
        return getGroupId();
    }

    @Override
    public Integer value2() {
        return getMessageId();
    }

    @Override
    public String value3() {
        return getMessageJson();
    }

    @Override
    public String value4() {
        return getRawMessageJson();
    }

    @Override
    public Timestamp value5() {
        return getLastUpdate();
    }

    @Override
    public RawdataRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public RawdataRecord value2(Integer value) {
        setMessageId(value);
        return this;
    }

    @Override
    public RawdataRecord value3(String value) {
        setMessageJson(value);
        return this;
    }

    @Override
    public RawdataRecord value4(String value) {
        setRawMessageJson(value);
        return this;
    }

    @Override
    public RawdataRecord value5(Timestamp value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public RawdataRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RawdataRecord
     */
    public RawdataRecord() {
        super(Rawdata.RAWDATA);
    }

    /**
     * Create a detached, initialised RawdataRecord
     */
    public RawdataRecord(Integer groupId, Integer messageId, String messageJson, String rawMessageJson, Timestamp lastUpdate) {
        super(Rawdata.RAWDATA);

        set(0, groupId);
        set(1, messageId);
        set(2, messageJson);
        set(3, rawMessageJson);
        set(4, lastUpdate);
    }
}
