# Base URL of the archive site, should end in /, or use / to use an absolute path against the current site
baseUrl=/
# true: Use absolute paths against baseUrl, all other values: use relative paths
useAbsolutePaths=false
# Base URL of the archive site for generating canonical URLs
canonicalBaseUrl=https://fb-list-archive.lawinegevaar.nl/
# true: Generate canonical links in pages
generateCanonicalLink=true
# Name of site, used in link names and titles
name=Firebird Groups Archive
# Language of the content, used in lang-attribute of html-tag
lang=en
# Url to parent site, used to link to parent site
parentSiteUrl=https://firebirdsql.org/
# Name for parent site, used in link names to parent site
parentSiteName=firebirdsql.org
# Introductory text on the root index
introduction=This archive contains the messages of various Firebird-related mailing lists which were hosted on Yahoo Groups. The archive only contains messages up to the 14th of December 2019, when Yahoo closed down the REST APIs to access this data.
# comma-separated list of URL prefixes that will have the rel="nofollow" attribute removed from an anchor
whitelistedUrlPrefixes=http://www.firebirdsql.org/,https://www.firebirdsql.org/,http://firebirdsql.org/,https://firebirdsql.org/
